import Sidebar from "@/components/sidebar/Sidebar";
import "./globals.css";
import { Roboto } from "next/font/google";
import Navbar from "@/components/navbar/Navbar";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "100", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <main className="flex">
          <div className="flex-2">
            <Sidebar />
          </div>

          <div className="lg:flex-8 w-full p-5">{children}
          <Navbar />
          </div>
        </main>
      </body>
    </html>
  );
}
